### PR TITLE
Add Select AI provider

### PR DESCRIPTION
**Pull request by tinoper**
Currently, users can choose between OpenAI and Gemini. We can add more options later if all goes well.
Here are a few observations:
For Gemini, I removed the Dall-E-like option.
There are some issues with using Gemini to handle the stream we receive with the library (This is where you can help with debugging). 

Screenshot 2024-08-31 at 20 09 23
Screenshot 2024-08-31 at 20 09 14

### CODE REVIEW

**Comment by arz03** [comment]
will this be merged into production branch? @davidmigloz

**Comment by davidmigloz** [comment]
@arz03 yes, let's see if I find a moment today to complete it

**Comment by arz03** [comment]
@davidmigloz any updates?

**Comment by davidmigloz** [comment]
@arz03 still on my TODO list 🥲

**Comment by arz03** [comment]
any progress?😅

**Comment by davidmigloz** [comment]
Google AI is finally available as a provider in https://pixels2flutter.dev/ 🥳
image

Thanks again for your work @tinoper!! And sorry for the long wait @arz03.

**Pull request merged**
